# Andrew Podhorecki
## 10/29/2020 WK10
### Python numpy Array Processing

In [1]:
import numpy as np

In [2]:
my_list = [11,22,33,44,55,66,77]

my_list

[11, 22, 33, 44, 55, 66, 77]

In [3]:
my_arr = np.array(my_list)

my_arr

array([11, 22, 33, 44, 55, 66, 77])

In [4]:
fruits = ['Orange', 'Apple', 'Cherry', 'Grape']

fruits

['Orange', 'Apple', 'Cherry', 'Grape']

In [5]:
# dtype='<U6' shows of type string

my_str_arr = np.array(fruits)

my_str_arr

array(['Orange', 'Apple', 'Cherry', 'Grape'], dtype='<U6')

In [6]:
# dtype='|S2' is string with 2 characters

my_arr2 = np.array([11,22,33,44,55], dtype='S')

my_arr2

array([b'11', b'22', b'33', b'44', b'55'], dtype='|S2')

In [7]:
my_arr3 = np.array([5,6,7,8,9], dtype='i4')

my_arr3

array([5, 6, 7, 8, 9])

In [8]:
# cannot convert 'c' to int

my_errorArr = np.array(['1','2','3','4','5','c'], dtype='i')

my_errorArr

ValueError: invalid literal for int() with base 10: 'c'

In [9]:
scores = [78.5,88.9,0.3,89.9]

scores_arr = np.array(scores)

print(scores_arr)

[78.5 88.9  0.3 89.9]


In [10]:
new_arr = scores_arr.astype('i')

print(new_arr)

[78 88  0 89]


In [11]:
# 0 is false
# all other numbers are true

bool_arr = np.array([1,0,1,1,8,0,13,0,0,1])

bool_arr

array([ 1,  0,  1,  1,  8,  0, 13,  0,  0,  1])

In [12]:
new_bool = bool_arr.astype(bool)

new_bool

array([ True, False,  True,  True,  True, False,  True, False, False,
        True])

In [13]:
lst1 = [1,2,3,4,5]
lst2 = [11,22,33,44,55]

listy = [lst1,lst2]

matrix = np.array(listy)

print(matrix)

[[ 1  2  3  4  5]
 [11 22 33 44 55]]


In [14]:
# numpy built in functions to generate arrays from existing arrays (instead of using =)
# copy (generates completely new array)
# view (will just show a copy view/ link of the primary array)

# copy:
my_lst = [11,12,13,14,15]

arr = np.array(my_lst)
copy_arr = arr.copy()

print(arr)
print(copy_arr)

[11 12 13 14 15]
[11 12 13 14 15]


In [15]:
arr[3] = 4

print(arr)
print(copy_arr)

[11 12 13  4 15]
[11 12 13 14 15]


In [16]:
#
# view:
#

my_lst = [11,12,13,14,15]

arr = np.array(my_lst)
view_arr = arr.view()

print(arr)
print(view_arr)

[11 12 13 14 15]
[11 12 13 14 15]


In [17]:
arr[3] = 4

print(arr)
print(view_arr)

[11 12 13  4 15]
[11 12 13  4 15]


In [18]:
# see if new or a base(what it points to)

print(copy_arr.base)
print(view_arr.base)

None
[11 12 13  4 15]


In [22]:
# shape (number of elements in each dimension)

lst1 = [1,2,3,4,5]
lst2 = [11,22,33,44,55]

my_lst = [lst1,lst2]

my_arr = np.array(my_lst)

print(my_arr)
print(my_arr.ndim)
print(my_arr.shape)

# shape returns 2 dimensions and each dimension has 5 elements

[[ 1  2  3  4  5]
 [11 22 33 44 55]]
2
(2, 5)


In [25]:
#specify number of dimensions to create

arr = np.array(lst1, ndmin=4)

print(arr)
print(arr.ndim)
print(arr.shape)

[[[[1 2 3 4 5]]]]
4
(1, 1, 1, 5)


In [26]:
arr = np.array(lst1, ndmin=6)

print(arr)
print(arr.ndim)
print(arr.shape)

[[[[[[1 2 3 4 5]]]]]]
6
(1, 1, 1, 1, 1, 5)


In [ ]:
# each index in the shape tells the number of elements in that dimension