# Andrew Podhorecki
## 10/27/2020 WK10
### Python numpy intro

In [1]:
# numpy allows for faster manipulation of matrices

import numpy as np

In [2]:
np.__version__

'1.18.5'

In [3]:
#generate array

array = np.array([1,2,3,4,5,6])

In [4]:
array

array([1, 2, 3, 4, 5, 6])

In [5]:
type(array)

numpy.ndarray

In [6]:
array2 = np.array((1,2,3,4,5,6))

In [7]:
array2

array([1, 2, 3, 4, 5, 6])

In [8]:
type(array2)

numpy.ndarray

In [9]:
# 0 Dimension Array, 1 element, scalars

array3 = np.array(50)

In [10]:
array3

array(50)

In [11]:
print(array3)

50


In [12]:
# 1 Dimension Array, has elements (most common), is just a list

array4 = np.array([1,2,3,4,5,6])
print(array4)

[1 2 3 4 5 6]


In [13]:
# 2 Dimension Array, Matrix

matrix = np.array([[1,2,3,4,5,6], [11,22,33,44,55,66]])
print(matrix)

[[ 1  2  3  4  5  6]
 [11 22 33 44 55 66]]


In [14]:
# 3 Dimension Array, Matrices

matrices = np.array( [ [[1,2,3], [4,5,6]], [[11,22,33], [44,55,66]] ] )
print(matrices)

[[[ 1  2  3]
  [ 4  5  6]]

 [[11 22 33]
  [44 55 66]]]


In [15]:
print(array3.ndim)

0


In [16]:
print(array4.ndim)

1


In [17]:
print(matrix.ndim)

2


In [18]:
print(matrices.ndim)

3


In [19]:
#
# Array Indexing 1D
#

In [20]:
print(array4[1])

2


In [21]:
print(array4[-1])

6


In [22]:
print(array4[1] + array4[5])

8


In [23]:
#
# Array Indexing 2D
# print(matrix[list][element])
#

In [24]:
print(matrix)

[[ 1  2  3  4  5  6]
 [11 22 33 44 55 66]]


In [25]:
print(matrix[0][1])

2


In [26]:
print(matrix[1][1])

22


In [27]:
print(matrix[1][5])

66


In [28]:
print(matrix[1][-1])

66


In [29]:
print(matrix[-1][-1])

66


In [30]:
print(matrix[0][0])

1


In [31]:
#
# Array Indexing 3D
# print(matrices[matrix][list][element])
#

In [32]:
print(matrices)

[[[ 1  2  3]
  [ 4  5  6]]

 [[11 22 33]
  [44 55 66]]]


In [33]:
print(matrices[0][1][-1])

6


In [34]:
print(matrices[1][1][1])

55


In [35]:
print(matrices[1][0][2])

33


In [36]:
#can also do like this
print(matrices[1,0,2])

33


In [37]:
# setting number of dimensions

my_array = np.array([1,2,3,4,5], ndmin = 5)
my_array

array([[[[[1, 2, 3, 4, 5]]]]])

In [38]:
my_array.ndim

5

In [39]:
#
# slicing numpy array
# includes element of start index but excludes element of end index
#
# [:end]        (will start at 0)
# [start:]      (will end at lentgh of array)
# [start:end]   (step is considered 1)
# [start:end:step]
#

In [40]:
print(array4)

[1 2 3 4 5 6]


In [41]:
print(array4[1:4])

[2 3 4]


In [42]:
print(array4[1:6])

[2 3 4 5 6]


In [43]:
print(array4[3:])

[4 5 6]


In [44]:
print(array4[:3])

[1 2 3]


In [45]:
print(array4[1:4:2])

[2 4]


In [46]:
print(array4[1:-1])

[2 3 4 5]


In [47]:
print(array4[3:0:-1])

[4 3 2]


In [48]:
print(array4[-3:-1])

[4 5]


In [49]:
print(array4[::2])

[1 3 5]


In [50]:
#
#
# 10/29/2020
#
#

In [53]:
# slicing 2D numpy matrix

print(matrix)

[[ 1  2  3  4  5  6]
 [11 22 33 44 55 66]]


In [54]:
print(matrix[1,1:3])

[22 33]


In [55]:
print(matrix[1][1:3])

[22 33]


In [58]:
print(matrix[0:2,3])

[ 4 44]


In [59]:
print(matrix[:,3])

[ 4 44]


In [60]:
print(matrix[:,1:3])

[[ 2  3]
 [22 33]]
