# Andrew Podhorecki
## 11/05/2020 WK11
### Python numpy unfunc

In [1]:
import numpy as np

arr1 = [1,2,3,4,5,6,7,8,9]

arr2 = [11,12,13,14,15,16,17,18]

z = []

# zip will join them

for i, j in zip(arr1,arr2):
    z.append(i + j)
    
z

[12, 14, 16, 18, 20, 22, 24, 26]

In [2]:
# zip
# will give tuple

fname = ("Alice", "Bob", "Christy")
lname = ("Charlie", "Clark", "Robert")
flname = zip(fname,lname)

print(tuple(flname))

(('Alice', 'Charlie'), ('Bob', 'Clark'), ('Christy', 'Robert'))


In [3]:
lst1 = [1,2,3,4,5]
lst2 = [10,11,12,13,14]

print(list(zip(lst1,lst2)))

[(1, 10), (2, 11), (3, 12), (4, 13), (5, 14)]


In [4]:
#
#
#

arr = np.arange(21)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [5]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595])

In [6]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
       4.85165195e+08])

In [7]:
# did not change array

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [9]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [10]:
#
#
# wk12
# 11/10/20
#
#

In [12]:
arr1 = np.array([[1,2],[2,4]])
arr2 = np.array([[5,6],[7,8]])
cond = np.array([[True,False],[True,True]])


#will get from arr1 if true, if false will get it from arr2
np.where(cond,arr1,arr2)

array([[1, 6],
       [2, 4]])

In [13]:
# can also pass code directly into where

np.where([[True,False],[True,True]],[[5,6],[7,8]],[[1,2],[2,4]])

array([[5, 2],
       [7, 8]])

In [16]:
# random

from numpy.random import randn

arr = randn(3,3)
arr

array([[ 1.45131846,  0.1876456 , -0.82253631],
       [ 1.95845488, -0.32368413,  1.83629244],
       [ 1.03733147, -0.40638549, -0.15590997]])

In [17]:
np.where(arr<0, 0, arr)

array([[1.45131846, 0.1876456 , 0.        ],
       [1.95845488, 0.        , 1.83629244],
       [1.03733147, 0.        , 0.        ]])

In [18]:
# any will return if any is true

arr_bool = np.array([True,False,True,False,False])

arr_bool.any()

True

In [19]:
# will return true if ALL elements in boolean array are true

arr_bool.all()

False

In [20]:
# unique removes duplicates

fruits = np.array(['Apple','Cherry','Apple','Orange','Cherry','Banana'])

np.unique(fruits)

array(['Apple', 'Banana', 'Cherry', 'Orange'], dtype='<U6')

In [22]:
# true if it exists in list

np.in1d(['Apple','Cherry','Grape'],fruits)

array([ True,  True, False])

In [23]:
# statistical matrixes

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
print(arr.shape)

(3, 3)


In [25]:
#total sum
arr.sum()

45

In [26]:
# sum of columns
arr.sum(0)

array([12, 15, 18])

In [27]:
#sum of rows
arr.sum(1)

array([ 6, 15, 24])

In [32]:
# same
np.sum(arr, axis=None)

45

In [30]:
# same
np.sum(arr, axis=0)

array([12, 15, 18])

In [31]:
# same
np.sum(arr, axis=1)

array([ 6, 15, 24])

In [33]:
# means

arr.mean()

5.0

In [34]:
arr.mean(0)

array([4., 5., 6.])

In [35]:
arr.mean(1)

array([2., 5., 8.])

In [36]:
# can do same with axis thing

#other stats stuff:

In [37]:
arr.var()

6.666666666666667

In [39]:
arr.std()

2.581988897471611

In [42]:
# sort specially 1d arrays

arr = np.array([3,6,8,1,9,10,3,5,69,7,8,2,5,13,11,13])

arr.sort()

arr

array([ 1,  2,  3,  3,  5,  5,  6,  7,  8,  8,  9, 10, 11, 13, 13, 69])

In [43]:
# identity array (matrix, treated as array)

i = np.eye(5)

i

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [45]:
a = np.arange(25).reshape((5,5))

a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [46]:
# will multiply scalars

a * i

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  6.,  0.,  0.,  0.],
       [ 0.,  0., 12.,  0.,  0.],
       [ 0.,  0.,  0., 18.,  0.],
       [ 0.,  0.,  0.,  0., 24.]])

In [50]:
i = np.eye(2)

a = np.arange(4).reshape((2,2))

print(i)

print(a)

print(a * i)

[[1. 0.]
 [0. 1.]]
[[0 1]
 [2 3]]
[[0. 0.]
 [0. 3.]]


In [51]:
m = np.mat([[1,2],[3,4]])

m

matrix([[1, 2],
        [3, 4]])

In [52]:
# treated as matrix * matrix, not matrix * array

m * i

matrix([[1., 2.],
        [3., 4.]])

In [53]:
# transpose, flips dimension of array, but does not change numbers

arr = np.array([[1,2,3,4],[5,6,7,8]])

print(arr.shape)
print(arr)
print("----------")

t = arr.T

t

(2, 4)
[[1 2 3 4]
 [5 6 7 8]]
----------


array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [54]:
# or can use arr.transpose()

arr.transpose()

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [55]:
arr.transpose(0,1)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [56]:
arr.transpose(1,0)

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [57]:
# with 3D

arr_3d = np.arange(20).reshape((2,5,2))

arr_3d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [58]:
print(arr_3d.shape)

(2, 5, 2)


In [59]:
arr_3d.transpose(0,1,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [60]:
arr_3d.transpose(2,1,0)

array([[[ 0, 10],
        [ 2, 12],
        [ 4, 14],
        [ 6, 16],
        [ 8, 18]],

       [[ 1, 11],
        [ 3, 13],
        [ 5, 15],
        [ 7, 17],
        [ 9, 19]]])

In [61]:
arr_3d.transpose(1,0,2)

array([[[ 0,  1],
        [10, 11]],

       [[ 2,  3],
        [12, 13]],

       [[ 4,  5],
        [14, 15]],

       [[ 6,  7],
        [16, 17]],

       [[ 8,  9],
        [18, 19]]])

In [62]:
arr_3d.transpose(2,0,1)

array([[[ 0,  2,  4,  6,  8],
        [10, 12, 14, 16, 18]],

       [[ 1,  3,  5,  7,  9],
        [11, 13, 15, 17, 19]]])

In [64]:
# more random funcs

np.random.random((4,4))

array([[0.69723857, 0.49633931, 0.92858294, 0.31809013],
       [0.97245361, 0.10111746, 0.88202375, 0.12817721],
       [0.63765553, 0.40496319, 0.40665538, 0.86571712],
       [0.82583964, 0.95468188, 0.75678744, 0.69918654]])

In [65]:
from numpy.random import random
random((4,4))

array([[0.43768921, 0.76739205, 0.58710702, 0.71030056],
       [0.23441596, 0.87602224, 0.3363969 , 0.40417817],
       [0.55782692, 0.58043375, 0.07745925, 0.84627685],
       [0.50023524, 0.55537829, 0.61376341, 0.33554833]])

In [66]:
from numpy.random import randn
randn(5,5)

array([[-1.35360984,  1.10609791,  0.20121359,  1.00679772, -0.15730511],
       [-0.72651471, -0.11714298,  1.27807265,  0.55416789,  1.4114112 ],
       [-1.49446472,  0.37669687, -0.11219221, -0.38268376, -1.22464962],
       [ 0.95765582, -1.90323992,  0.5442145 , -0.34860041,  0.41973559],
       [-0.42720048,  0.00558931,  0.95464956, -0.59267927,  0.68839111]])

In [67]:
randn(5)

array([-0.33027332,  1.64703668,  1.23671878,  0.18248753, -0.26543397])

In [68]:
np.random.randint(10,50)

39

In [69]:
# go to this site for all universal functions

website = "https://numpy.org/doc/stable/reference/ufuncs.html"

import webbrowser

webbrowser.open(website)

True

In [70]:
# pandas (open source python library, easy to use data analysis)

import pandas as pd