# Andrew Podhorecki
## 11/03/2020 WK11
### Python numpy creating, transporting, and processing arrays

In [1]:
import numpy as np

arr_2d = np.array([[1,2,3,4],[5,6,7,8]])

print(arr_2d)
print(arr_2d.ndim)
print(arr_2d.shape)
print(arr_2d.dtype)

[[1 2 3 4]
 [5 6 7 8]]
2
(2, 4)
int32


In [2]:
# using zeros to create array with size (x)

arr = np.zeros(10)
print(arr)
print(arr.dtype)
print(arr.ndim)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
float64
1


In [3]:
arr_2d = np.zeros((5,5))

print(arr_2d)
print(arr_2d.dtype)
print(arr_2d.ndim)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
float64
2


In [4]:
# create but with all ones

arr_2d = np.ones((5,5))

print(arr_2d)
print(arr_2d.dtype)
print(arr_2d.ndim)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
float64
2


In [5]:
# generate empty arrays and dtype

arr_2d = np.empty((2,2))

print(arr_2d)
print(arr_2d.dtype)
print(arr_2d.ndim)

[[4.24399158e-314 8.48798317e-314]
 [1.27319747e-313 1.69759663e-313]]
float64
2


In [6]:
# arange: creates a range

# one dimension array from 0 to 9
arr = np.arange(10)

print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
arr = np.arange(10,101,5)

print(arr)
print(arr.shape)
print(arr.dtype)
print(arr.ndim)

[ 10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90  95
 100]
(19,)
int32
1


In [8]:
arr = np.arange(1,13)

print(arr)
print(arr.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)


In [9]:
# reshape: ex will print matrix with 3 elemnts in 1d and 4 in 2nd dimension

arr_2d = arr.reshape(3,4)

print(arr_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [10]:
arr_2d = arr.reshape(4,3)

print(arr_2d)
print(arr_2d.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


In [11]:
# reshape 1d to 3d
# cannot exceed 12 total in this case as arr has 12

arr_3d = arr.reshape(3,2,2)

print(arr_3d)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [12]:
arr_3d = arr.reshape(2,3,2)

print(arr_3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [13]:
# reshape is a view or a copy

print(arr_3d.base)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [14]:
# can pass '-1' in the 1d ONLY and python 'figures it out'

arr_3d = arr.reshape(2,3,-1)

print(arr_3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [15]:
# flattens array into 1d

arr = np.array([[1,2,3,4],[5,6,7,8]])

In [16]:
arr.reshape(-1)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [17]:
# iterating 1d scalars

arr = np.arange(10)

print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [18]:
for n in arr:
    print(n)

0
1
2
3
4
5
6
7
8
9


In [19]:
# iterating 2d

arr_2d = np.array([[1,2,3,4],[5,6,7,8]])

for n in arr_2d:
    print(n)

[1 2 3 4]
[5 6 7 8]


In [20]:
for n in arr_2d:
    for x in n:
        print(x)

1
2
3
4
5
6
7
8


In [21]:
# iterating 3d

arr = np.arange(12)

arr_3d = arr.reshape(2,2,3)

for n in arr_3d:
    print(n)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [22]:
for n in arr_3d:
    for x in n:
        print(x)

[0 1 2]
[3 4 5]
[6 7 8]
[ 9 10 11]


In [23]:
for n in arr_3d:
    for x in n:
        for z in x:
            print(z)

0
1
2
3
4
5
6
7
8
9
10
11


In [24]:
# method in numpy will get to and prints/ iterates each scalar
# nditer()

for n in np.nditer(arr_3d):
    print(n)

0
1
2
3
4
5
6
7
8
9
10
11


In [25]:
for n in np.nditer(arr_2d):
    print(n)

1
2
3
4
5
6
7
8


In [26]:
# skipping elements

arr_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [27]:
arr_2d[:,::2]

array([[1, 3],
       [5, 7]])

In [28]:
for n in np.nditer(arr_2d[:,::2]):
    print(n)

1
3
5
7


In [29]:
# printing indexes

arr = np.arange(1,13)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [30]:
for index, n in np.ndenumerate(arr):
    print(index, n)

(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5
(5,) 6
(6,) 7
(7,) 8
(8,) 9
(9,) 10
(10,) 11
(11,) 12


In [31]:
arr_2d = np.array([[1,2],[3,4],[5,6],[7,8]])

print(arr_2d)
print(arr_2d.shape)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)


In [32]:
# shows position and scalar 2d matrix

for i, v in np.ndenumerate(arr_2d):
    print(i, v)

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4
(2, 0) 5
(2, 1) 6
(3, 0) 7
(3, 1) 8


In [33]:
# multiplying arrays

print(arr_2d)

arr_2d * arr_2d

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


array([[ 1,  4],
       [ 9, 16],
       [25, 36],
       [49, 64]])

In [34]:
arr_2d - arr_2d

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [35]:
arr_2d + arr_2d

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16]])

In [36]:
arr_2d / arr_2d

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [37]:
arr_2d ^ 3

array([[ 2,  1],
       [ 0,  7],
       [ 6,  5],
       [ 4, 11]], dtype=int32)

In [38]:
# indexing

arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [39]:
arr[1:6]

array([2, 3, 4, 5, 6])

In [40]:
arr[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [41]:
arr[::3] # skipping every 3

array([ 1,  4,  7, 10])

In [42]:
arr[0:6] = 100

arr

array([100, 100, 100, 100, 100, 100,   7,   8,   9,  10,  11,  12])

In [44]:
#
# 11/5/2020
#

arr_2d = np.array([[5,10,25],[15,10,20],[20,30,25]])

print(arr_2d.shape)
print(arr_2d)

(3, 3)
[[ 5 10 25]
 [15 10 20]
 [20 30 25]]


In [45]:
arr_2d[1]

array([15, 10, 20])

In [47]:
arr_2d[1][0]

15

In [48]:
# slicing recap

arr_2d[:2,1:]

array([[10, 25],
       [10, 20]])

In [50]:
#

arr = np.zeros((9,9))

arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [51]:
arr.shape

(9, 9)

In [52]:
arr.shape[0]

9

In [54]:
arr.shape[1]

9

In [57]:
l = arr.shape[0]

for index in range(l):
    arr[index] = 10
    
arr

array([[10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.]])

In [58]:
for index in range(l):
    arr[index] = index * 2
    
arr

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [12., 12., 12., 12., 12., 12., 12., 12., 12.],
       [14., 14., 14., 14., 14., 14., 14., 14., 14.],
       [16., 16., 16., 16., 16., 16., 16., 16., 16.]])

In [59]:
arr[1:7,3:6]

array([[ 2.,  2.,  2.],
       [ 4.,  4.,  4.],
       [ 6.,  6.,  6.],
       [ 8.,  8.,  8.],
       [10., 10., 10.],
       [12., 12., 12.]])

In [61]:
# fancy indexing
# pass parameters as a list

arr[[1,6,7]]

array([[ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [12., 12., 12., 12., 12., 12., 12., 12., 12.],
       [14., 14., 14., 14., 14., 14., 14., 14., 14.]])

In [62]:
arr[[3,5]]

array([[ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.]])

In [65]:
# reshape (must have exact number multiple) (ex 9 * 5 = 45)

arr = np.arange(45).reshape(9,5)

arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44]])

In [67]:
# flip columns and rows
# transpose

arr_t = arr.T

arr_t

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44]])

In [68]:
# multiplies together

np.dot(arr_t,arr)

array([[5100, 5280, 5460, 5640, 5820],
       [5280, 5469, 5658, 5847, 6036],
       [5460, 5658, 5856, 6054, 6252],
       [5640, 5847, 6054, 6261, 6468],
       [5820, 6036, 6252, 6468, 6684]])

In [69]:
arr_3d = np.arange(45).reshape(3,5,3)

arr_3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]],

       [[30, 31, 32],
        [33, 34, 35],
        [36, 37, 38],
        [39, 40, 41],
        [42, 43, 44]]])

In [70]:
# swap axes

arr = np.array([[1,2,3]])

arr

array([[1, 2, 3]])

In [71]:
arr.swapaxes(0,1)

array([[1],
       [2],
       [3]])

In [74]:
arr1 = np.random.randn(10)

arr1

array([-0.7131988 , -0.13443652, -0.85570109,  1.13868578,  0.15423227,
        0.38104927, -1.11044431,  0.62289493,  0.11255141,  0.987967  ])

In [75]:
arr2 = np.random.randn(10)

arr2

array([ 1.63215957, -0.70483866,  0.10947015, -0.73293812,  1.40914722,
        1.08477556,  0.10798177,  0.86445041,  0.31004588, -1.19297427])

In [76]:
# adds the arrays

np.add(arr1,arr2)

array([ 0.91896077, -0.83927518, -0.74623094,  0.40574765,  1.56337949,
        1.46582483, -1.00246254,  1.48734534,  0.42259729, -0.20500727])

In [77]:
# gives the max of the array values at that index

np.maximum(arr1,arr2)

array([ 1.63215957, -0.13443652,  0.10947015,  1.13868578,  1.40914722,
        1.08477556,  0.10798177,  0.86445041,  0.31004588,  0.987967  ])

In [78]:
# operations with conditions
# np.where

arr = np.arange(9).reshape((3,3))

arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [79]:
print(arr < 4)

[[ True  True  True]
 [ True False False]
 [False False False]]


In [82]:
# prints all values less than 4 as -1 and all else as 10

print(np.where(arr<4, -1, 10))

[[-1 -1 -1]
 [-1 10 10]
 [10 10 10]]


In [84]:
np.where((arr<4) & (arr>2),-1,-2)

array([[-2, -2, -2],
       [-1, -2, -2],
       [-2, -2, -2]])

In [88]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

arr_bool = np.array([True,False,True,True,False])

print(arr1)
print(arr2)
print(arr_bool)

print(list(zip(arr1,arr2,arr_bool)))

[1 2 3 4 5]
[10 20 30 40 50]
[ True False  True  True False]
[(1, 10, True), (2, 20, False), (3, 30, True), (4, 40, True), (5, 50, False)]


In [86]:
# using list comprehension (diffcult)

arr3 = [r1 if c else r2 for r1,r2,c in zip(arr1,arr2,arr_bool)]

arr3

[1, 20, 3, 4, 50]

In [91]:
# much easier

arr3 = np.where(arr_bool,arr1,arr2)

arr3

array([ 1, 20,  3,  4, 50])