# Andrew Podhorecki
## 11/03/2020 WK11
### Python numpy creating, transporting, and processing arrays

In [2]:
import numpy as np

arr_2d = np.array([[1,2,3,4],[5,6,7,8]])

print(arr_2d)
print(arr_2d.ndim)
print(arr_2d.shape)
print(arr_2d.dtype)

[[1 2 3 4]
 [5 6 7 8]]
2
(2, 4)
int32


In [6]:
# using zeros to create array with size (x)

arr = np.zeros(10)
print(arr)
print(arr.dtype)
print(arr.ndim)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
float64
1


In [10]:
arr_2d = np.zeros((5,5))

print(arr_2d)
print(arr_2d.dtype)
print(arr_2d.ndim)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
float64
2


In [15]:
# create but with all ones

arr_2d = np.ones((5,5))

print(arr_2d)
print(arr_2d.dtype)
print(arr_2d.ndim)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
float64
2


In [17]:
# generate empty arrays and dtype

arr_2d = np.empty((2,2))

print(arr_2d)
print(arr_2d.dtype)
print(arr_2d.ndim)

[[4.24399158e-314 8.48798317e-314]
 [1.27319747e-313 1.69759663e-313]]
float64
2


In [21]:
# arange: creates a range

# one dimension array from 0 to 9
arr = np.arange(10)

print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [27]:
arr = np.arange(10,101,5)

print(arr)
print(arr.shape)
print(arr.dtype)
print(arr.ndim)

[ 10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90  95
 100]
(19,)
int32
1


In [31]:
arr = np.arange(1,13)

print(arr)
print(arr.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)


In [32]:
# reshape: ex will print matrix with 3 elemnts in 1d and 4 in 2nd dimension

arr_2d = arr.reshape(3,4)

print(arr_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [35]:
arr_2d = arr.reshape(4,3)

print(arr_2d)
print(arr_2d.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


In [37]:
# reshape 1d to 3d
# cannot exceed 12 total in this case as arr has 12

arr_3d = arr.reshape(3,2,2)

print(arr_3d)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [38]:
arr_3d = arr.reshape(2,3,2)

print(arr_3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [39]:
# reshape is a view or a copy

print(arr_3d.base)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [40]:
# can pass '-1' in the 1d ONLY and python 'figures it out'

arr_3d = arr.reshape(2,3,-1)

print(arr_3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [43]:
# flattens array into 1d

arr = np.array([[1,2,3,4],[5,6,7,8]])

In [44]:
arr.reshape(-1)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [45]:
# iterating 1d scalars

arr = np.arange(10)

print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [46]:
for n in arr:
    print(n)

0
1
2
3
4
5
6
7
8
9


In [47]:
# iterating 2d

arr_2d = np.array([[1,2,3,4],[5,6,7,8]])

for n in arr_2d:
    print(n)

[1 2 3 4]
[5 6 7 8]


In [48]:
for n in arr_2d:
    for x in n:
        print(x)

1
2
3
4
5
6
7
8


In [52]:
# iterating 3d

arr = np.arange(12)

arr_3d = arr.reshape(2,2,3)

for n in arr_3d:
    print(n)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [53]:
for n in arr_3d:
    for x in n:
        print(x)

[0 1 2]
[3 4 5]
[6 7 8]
[ 9 10 11]


In [54]:
for n in arr_3d:
    for x in n:
        for z in x:
            print(z)

0
1
2
3
4
5
6
7
8
9
10
11


In [55]:
# method in numpy will get to and prints/ iterates each scalar
# nditer()

for n in np.nditer(arr_3d):
    print(n)

0
1
2
3
4
5
6
7
8
9
10
11


In [56]:
for n in np.nditer(arr_2d):
    print(n)

1
2
3
4
5
6
7
8


In [57]:
# skipping elements

arr_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [59]:
arr_2d[:,::2]

array([[1, 3],
       [5, 7]])

In [62]:
for n in np.nditer(arr_2d[:,::2]):
    print(n)

1
3
5
7


In [63]:
# printing indexes

arr = np.arange(1,13)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [64]:
for index, n in np.ndenumerate(arr):
    print(index, n)

(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5
(5,) 6
(6,) 7
(7,) 8
(8,) 9
(9,) 10
(10,) 11
(11,) 12


In [65]:
arr_2d = np.array([[1,2],[3,4],[5,6],[7,8]])

print(arr_2d)
print(arr_2d.shape)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)


In [67]:
# shows position and scalar 2d matrix

for i, v in np.ndenumerate(arr_2d):
    print(i, v)

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4
(2, 0) 5
(2, 1) 6
(3, 0) 7
(3, 1) 8


In [75]:
# multiplying arrays

print(arr_2d)

arr_2d * arr_2d

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


array([[ 1,  4],
       [ 9, 16],
       [25, 36],
       [49, 64]])

In [69]:
arr_2d - arr_2d

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [70]:
arr_2d + arr_2d

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16]])

In [71]:
arr_2d / arr_2d

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [73]:
arr_2d ^ 3

array([[ 2,  1],
       [ 0,  7],
       [ 6,  5],
       [ 4, 11]], dtype=int32)

In [76]:
# indexing

arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [77]:
arr[1:6]

array([2, 3, 4, 5, 6])

In [78]:
arr[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [79]:
arr[::3] # skipping every 3

array([ 1,  4,  7, 10])

In [80]:
arr[0:6] = 100

arr

array([100, 100, 100, 100, 100, 100,   7,   8,   9,  10,  11,  12])